# 1.Create a one-dimensional ndarray object with a length of 10 and all 0s, and then make the fifth element equal to 1

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt

%matplotlib inline
s1 = np.zeros(shape = 10)
s1
s1[4] = 1
print(s1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2.Create an ndarray object elements from 10 to 49

In [2]:
np.random.randint(10,50,size=10)
np.linspace(10,49,10)
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3.Reverse the position of all the elements of question 2

In [3]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 4.Use np.random.random to create a 10*10 ndarray object and print out the largest and smallest elements

In [4]:
a4 = np.random.random(size = (10,10))
a4
zmin,zmax=a4.min(),a4.max()
print(zmin,zmax)

0.019505573247546426 0.9857371025280236


# 5.Create a 1010 ndarray object, and the matrix boundary is all 1, and the inside is all 0

In [5]:
nd = np.zeros(shape = (10, 10),dtype = np. int8)
nd[[0,9]] = 1

nd[:,[0,9]] = 1
print(nd)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 6.Create a 5*5 matrix with each row from 0 to 4

In [6]:
a = [0,1,2,3,4]
nd = np.array(a*5)
print(nd.reshape(5,5))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 7.Create an arithmetic sequence of length 12 between (0, 1)

In [7]:
print(np.linspace(0,1,12))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


# 8.Create a random array of length 10 and sort

In [11]:
a8 = np.random.random(10)
a8
np.sort(a8)
a8.argsort()
print(a8[a8.argsort()])

[0.09852863 0.19363443 0.1938152  0.24471435 0.3042398  0.58107638
 0.66118875 0.74115208 0.8107587  0.82609923]


# 9.Create a random array of length 10 and replace the maximum value with 0

In [8]:
nd = np.random.randint(0,10,size = 10)
display(nd)
index_max= nd.argmax()
nd[index_max]
all_index_max = np.argwhere(nd==nd[index_max]).reshape(-1)
all_index_max
nd[all_index_max]=-100
print(nd)

array([3, 7, 9, 9, 7, 3, 3, 3, 2, 9])

[   3    7 -100 -100    7    3    3    3    2 -100]


# 10.How to sort a 5*5 matrix according to the third column?

In [9]:
n10=np.random.randint(0,100,size=(5,5))
n10
n10[:,2]
np.argsort(n10[:,2])
print(n10[np.argsort(n10[:,2])])

[[83 64  6 61 19]
 [48 93 12 11 15]
 [28 75 26 83 82]
 [72 29 52 99  7]
 [58 93 90 79 71]]


# 11.Given a 4-dimensional matrix, how to get the sum of the last two dimensions?

In [10]:
n11=np.random. randint(0, 100, size=(2,3,3,3))
n11
n11.sum(axis=(2,3))
print(n11. sum(axis=(-1,-2)))

[[474 419 474]
 [473 391 416]]


# 12.Given an array [1, 2, 3, 4, 5], how to get a new array with 3 zeros inserted between each element of this array?

In [12]:
nd1 = np.arange(1,6)
nd2 = np.zeros(shape=17,dtype=int)
nd2[::4] = nd1
print(nd2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


# 13.Given a two-dimensional matrix, how to exchange the elements of two rows?

In [13]:
np13=np.random.randint(0,100,size=(3,3))
print(np13)

[[22 91 85]
 [89 15  8]
 [50 47 17]]


# 14.Create a random array with a length of 100,000, use two methods to square it, and compare the time taken

In [14]:
n14=np.random.random(size=100000)
n14
n14=np.random.randint(0,100000,(5))
n14
%timeit np.power(n14,3)
%timeit n14**3
n14_2=np.dot(n14,n14)
%timeit np.dot(n14_2,n14)

2.05 µs ± 585 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.17 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
4.27 µs ± 883 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 15.Create a 53 random matrices and a 32 Random matrix, find matrix product

In [15]:
n15_53=np.random.randint(0,100,size=(5,3))
n15_53
n15_32 = np.random.randint(0,100,(3,2))
n15_32
print(np.dot(n15_53,n15_32))

[[ 6057  6941]
 [ 6360  7971]
 [ 7344  6984]
 [ 4897  4781]
 [ 8799 11948]]


# 16.The elements of each row of the matrix are subtracted from the average value of the row

In [16]:
n16 = np.random.randint(0,10,(3,3))
n16
n16_1 = n16.mean(axis=1).reshape(3,1)
n16_1
print(n16-n16_1)

[[ 1.66666667  0.66666667 -2.33333333]
 [-2.66666667  1.33333333  1.33333333]
 [-0.33333333 -0.33333333  0.66666667]]


# 17.Print out the following function (required to use np.zeros to create an 8*8 matrix):
* [[0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]]

In [17]:
nd=np.ones(shape = (8,8),dtype=int)
nd[::2,::2]=0
nd[1::2,1::2]=0
print(nd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 18.Regularize a 55 random matrix [Regular concept: Assuming that a is an element in the matrix, max/min are the maximum and minimum values ​​of the matrix elements respectively, then a = (a-min)/(max -min)]

In [18]:
n18 = np.random.randint(0,100,(5,5))
n18
nmax,nmin=n18.max(),n18.min()
nmax,nmin
n18=(n18-nmin)/(nmax-nmin)
print(n18)

[[0.76404494 0.8988764  0.50561798 0.         0.69662921]
 [0.84269663 0.08988764 0.35955056 0.82022472 0.        ]
 [0.38202247 0.48314607 0.39325843 0.33707865 0.61797753]
 [0.28089888 0.92134831 0.31460674 0.65168539 1.        ]
 [0.24719101 0.42696629 0.21348315 0.74157303 0.34831461]]


# 19.Convert a one-dimensional array into a binary representation matrix. E.g [1,2,3] is converted to

* [[0,0,1],
* [0,1,0],
* [0,1,1]]

In [19]:
1 and 0
1 or 1
1 & 2

0

# 20 realize the bubble sort method
* n=[19,60,66,71,54,57,1,24,82,39]

In [20]:
n20=[19,60,66,7154,57,1,24,82,39]
for i in range(len(n20)-1):
    for j in range (len(n20)-i-1):
        if  n20[j]>n20[j+1]:
            n20[j],n20[j+1]=n20[j+1],n20[j]
print(n20)

[1, 19, 24, 39, 57, 60, 66, 82, 7154]
