In [23]:
#How to convert a float (32 bits) array into an integer (32 bits) in place
import numpy as np
s = np.arange(8, dtype=np.int32)
s = s.astype(np.float32, copy=False)
print(s)

[0. 1. 2. 3. 4. 5. 6. 7.]


In [24]:
#Create a 3x3 matrix with values ranging from 0 to 8
s =  np.arange(0, 9).reshape(3,3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
s = np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4], dtype=int64),)


In [26]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
s = np.diag(1+np.arange(4), k = -1)
print (s)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
#Create a 10x10x10 array with random values
matrx = np.random.randint(10,size=(10,10,10))
print(matrx)

[[[5 4 8 1 1 0 1 8 3 3]
  [8 8 6 1 5 4 7 2 6 4]
  [6 5 8 3 5 1 6 1 8 8]
  [0 8 1 6 8 6 7 9 1 1]
  [3 8 8 2 4 6 7 5 3 7]
  [2 1 7 3 0 2 7 7 1 5]
  [9 0 3 9 0 6 8 5 4 4]
  [0 1 5 6 5 6 6 3 4 6]
  [9 2 0 2 0 5 2 6 0 5]
  [7 6 6 7 2 3 3 3 0 6]]

 [[4 1 0 3 4 5 3 8 4 9]
  [0 8 1 6 7 6 6 4 9 1]
  [0 1 5 6 8 9 2 3 6 3]
  [6 4 4 5 4 2 5 2 1 9]
  [8 4 1 7 1 3 7 8 4 5]
  [8 1 9 2 9 2 8 8 4 6]
  [5 4 1 1 3 2 6 2 8 1]
  [6 3 6 2 5 7 6 8 2 2]
  [2 8 4 7 1 7 3 2 1 3]
  [1 0 6 3 2 7 0 0 5 9]]

 [[3 7 5 2 5 0 2 2 5 3]
  [1 6 9 1 0 4 8 3 4 5]
  [4 7 4 9 1 8 5 7 8 8]
  [0 6 5 2 0 3 1 4 9 8]
  [7 6 9 7 8 8 6 7 4 7]
  [2 8 1 0 6 1 2 6 6 7]
  [2 7 5 3 0 4 0 7 1 0]
  [8 1 8 5 8 5 2 4 7 7]
  [1 2 7 7 5 3 1 0 6 8]
  [5 9 1 6 4 8 2 7 8 7]]

 [[0 7 2 9 8 0 5 1 4 6]
  [0 6 0 3 8 1 4 8 7 2]
  [7 9 7 2 2 5 2 8 3 5]
  [7 6 0 0 4 9 5 8 8 8]
  [8 1 4 1 9 0 6 1 4 3]
  [8 3 4 2 3 9 5 8 1 9]
  [4 5 8 4 5 8 3 6 4 6]
  [3 4 1 0 1 0 4 0 9 2]
  [8 4 0 5 2 1 6 1 3 8]
  [8 4 7 7 9 7 7 3 7 0]]

 [[9 7 6 0 7 0 8 5 1 4]
  [0 5 8

In [28]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
s = np.zeros ((8,8), dtype=int)
s[1::2, ::2]= 1
s[::2, 1::2] = 1
print (s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.96969668 0.36906585 0.90689354 0.02014739 0.42086229 0.75971165
  0.23657465 0.73288511 0.28195352 0.38517689]
 [0.26127707 0.18595386 0.92205632 0.81980813 0.15123682 0.88558983
  0.68416191 0.35829179 0.31504119 0.59019225]
 [0.79427006 0.60019412 0.19472827 0.65276791 0.12916225 0.64500836
  0.40922682 0.14114649 0.55004875 0.39987666]
 [0.84212565 0.45215202 0.86817803 0.18249255 0.65411924 0.48401528
  0.53670902 0.67992658 0.84507892 0.24198547]
 [0.8327775  0.35259167 0.38318231 0.89673999 0.49439856 0.03008903
  0.01093013 0.20944513 0.01098584 0.29954366]
 [0.35169321 0.98473976 0.11194815 0.84612446 0.37764439 0.46929586
  0.52900367 0.1774553  0.62576193 0.26939063]
 [0.33892287 0.97133354 0.70504385 0.77500367 0.81101376 0.19100181
  0.10893821 0.34273664 0.81576752 0.04738526]
 [0.52920576 0.54655579 0.08675663 0.18994037 0.09851115 0.28616139
  0.88844034 0.57911124 0.88509164 0.61634978]
 [0.79996611 0.31947095 0.84545398 0.70801761 0.65281958 0.34875864
  0.43335218

In [30]:
## Create a 10x10 matrix with row values ranging from 0 to 9
i = np.zeros((10,10))
i += np.arange(10)
print(i)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [31]:
##Consider two random matrices A anb B, check if they are equal.
A = np.random.randint(0,1,4)
B = np.random.randint(0,1,4)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

True
True


In [32]:
##Create a random vector of size 1000 and find the mean value
s = np.random.random(1000)
me = s.mean()
print (me)

0.49042674972740924


In [33]:
##Create random vector of size 100 and replace the maximum value by 0
x = np.random.random(1000)
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

[8.46073345e-01 4.20178916e-01 4.84632638e-01 9.20304859e-01
 5.51570092e-01 1.07913138e-01 5.49457342e-01 1.64284315e-01
 5.31651303e-01 9.10295705e-01 3.97009462e-01 8.74893861e-01
 5.08355668e-01 1.40961768e-01 9.11473108e-01 9.18834683e-01
 8.72931635e-01 2.21157061e-01 2.27459737e-01 2.15455745e-01
 2.54029372e-02 2.27775077e-02 6.94146481e-01 8.17048692e-02
 8.26694545e-01 7.93519414e-01 8.67412731e-01 9.59361707e-01
 5.24244263e-01 5.44717499e-01 6.15161302e-01 1.89492074e-01
 4.78116199e-01 2.00436610e-01 6.00576608e-01 2.92514649e-01
 4.10926286e-01 4.67135663e-01 1.65581430e-01 8.72383966e-02
 3.70037497e-01 9.80779956e-01 5.82630035e-01 2.99385595e-01
 8.27091259e-01 9.98143719e-02 3.26989635e-01 3.30707117e-01
 5.68623628e-01 7.90683526e-01 9.17400026e-01 1.35995058e-01
 7.44743538e-01 6.41377727e-01 8.41796457e-01 8.63083949e-01
 4.06248990e-01 3.40751201e-01 3.02407017e-01 4.30786375e-01
 3.66036620e-01 3.75582834e-01 3.33745404e-01 7.77648588e-01
 4.46800168e-01 3.577295

In [34]:
##Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [35]:
##Following is the provided numPy array. Return array of items by taking the third column from all rows
#sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


In [36]:
##Return array of odd rows and even columns from below numpy array
#sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
new_Array = sampleArray[::2, 1::2]
print(new_Array)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


In [37]:
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
##arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
###arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in np.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [38]:
##Split the array into four equal-sized sub-arrays
##Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
Array = np.arange(10, 34, 1)
Array = Array.reshape(8,3)
print (Array)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(Array, 4) 
print(subArrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [39]:
#Sort following NumPy array
##Case 1: Sort array by the second row
###Case 2: Sort the array by the second column
####sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

sort_Array_ByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sort_Array_ByRow)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [40]:
#Print max from axis 0 and min from axis 1 from the following 2-D array.
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

min_OfAxisOne = np.amin(sampleArray, 1) 
print("Printing min Of Axis 1")
print(min_OfAxisOne)

max_OfAxisOne = np.amax(sampleArray, 0) 
print("Printing max Of Axis 0")
print(max_OfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing min Of Axis 1
[34 12 53]
Printing max Of Axis 0
[82 94 73]


In [41]:
#Delete the second column from a given array and insert the following new column in its place.
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
###newColumn = numpy.array([[10,10,10]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [42]:
##Create two 2-D arrays and Plot them using matplotlib